name: CD

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando CD
        uses: actions/upload-artifact@v2
        with:
          name: DevOps
          path: |
            **/*.py
            README.md
            requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: deliver

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v3
        with:
          name: DevOps

      - name: Exibir estrutura dos arquivos baixados
        run: ls -R
