name: CD

on:
  push

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Check out repository code
        uses: actions/checkout@v4

      - 
        name: Simulando CD
        uses: actions/upload-artifact@v4
        with:
          name: DevOps
          path: |
            '**.py'
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver

    steps:
      - 
        name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: DevOps

      -
        name: Exibir estrutura dos arquivos baixados
        run: ls -R